In [32]:
from keras.models import Sequential
from keras.layers import SimpleRNN
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import SimpleRNN
tf.enable_eager_execution()  

ValueError: tf.enable_eager_execution must be called at program startup.

In [9]:
model=Sequential()
model.add(SimpleRNN(3,input_shape=(2,10)))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [11]:
model=Sequential()
model.add(SimpleRNN(3,batch_input_shape=(3,2,10),return_sequences=True))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (3, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [12]:
model=Sequential()
model.add(SimpleRNN(3,batch_input_shape=(8,2,10),return_sequences=True))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_4 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


각 타임 스탬프마다 리턴을 받으려면 3d(return_sequence=True)로 , 마지막에만 받으려면 2d로

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import SimpleRNN
tf.enable_eager_execution()

In [2]:
train_X=[[0.1,42.,1.5,1.1,2.8],[1.0,3.1,2.5,0.7,1.1],[0.3,2.1,1.5,2.1,0.1],[2.1,1.4,0.5,0.9,1.1]]
print(np.shape(train_X))

(4, 5)


In [3]:
train_X=[[[0.1,4.2,1.5,1.1,2.8],[1.0,3.1,2.5,0.7,1.1],[0.3,2.1,1.5,2.1,0.1],[2.1,1.4,0.5,0.9,1.1]]]

train_X=np.array(train_X,dtype=np.float32)

print(train_X.shape)

(1, 4, 5)


In [4]:

rnn=SimpleRNN(3,return_sequences=True,return_state=True)

hidden_states,last_states=rnn(train_X)

hidden_states   # 3으로 설정해줘서 3차원


<tf.Tensor: id=171, shape=(1, 4, 3), dtype=float32, numpy=
array([[[-0.64906   ,  0.98363465,  0.6506858 ],
        [ 0.51655006,  0.8700812 , -0.31797504],
        [ 0.93289584, -0.10392687, -0.4718843 ],
        [-0.11030142, -0.9122978 ,  0.94773203]]], dtype=float32)>

In [5]:
last_states

<tf.Tensor: id=157, shape=(1, 3), dtype=float32, numpy=array([[-0.11030142, -0.9122978 ,  0.94773203]], dtype=float32)>

In [22]:
text='나랑 점심 먹으러 갈래 메뉴는 햄버거 점심 메뉴 좋지'

In [23]:
#토큰화와 정수 인코딩

from keras_preprocessing.text import Tokenizer
t=Tokenizer()
t.fit_on_texts([text])

encoded=t.texts_to_sequences([text])[0]

In [ ]:
encoded

In [24]:
vocab_size=len(t.word_index)+1



In [25]:
t.word_index

{'점심': 1, '나랑': 2, '먹으러': 3, '갈래': 4, '메뉴는': 5, '햄버거': 6, '메뉴': 7, '좋지': 8}

In [26]:
sequences=list()
for c in range(1,len(encoded)):
    sequence=encoded[c-1:c+1]
    sequences.append(sequence)
    
print(len(sequences))

8


In [48]:
sequences

[[2, 1], [1, 3], [3, 4], [4, 5], [5, 6], [6, 1], [1, 7], [7, 8]]

In [53]:
import numpy as np

X,y=zip(*sequences)
X=np.array(X)
y=np.array(y)

In [54]:
print(X)
print(y)

[2 1 3 4 5 6 1 7]
[1 3 4 5 6 1 7 8]


In [55]:
from keras.utils import to_categorical
y=to_categorical(y,num_classes=vocab_size)
print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [29]:
from keras.layers import Embedding,Dense,SimpleRNN
from keras.models import Sequential
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

In [56]:
model=Sequential()
model.add(Embedding(vocab_size,9,input_length=1))

model.add(SimpleRNN(9))

model.add(Dense(vocab_size,activation='softmax'))

In [31]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=500,verbose=2)

Epoch 1/500
 - 1s - loss: 2.2134 - acc: 0.0000e+00
Epoch 2/500
 - 0s - loss: 2.2106 - acc: 0.0000e+00
Epoch 3/500
 - 0s - loss: 2.2078 - acc: 0.1250
Epoch 4/500
 - 0s - loss: 2.2050 - acc: 0.1250
Epoch 5/500
 - 0s - loss: 2.2022 - acc: 0.2500
Epoch 6/500
 - 0s - loss: 2.1995 - acc: 0.2500
Epoch 7/500
 - 0s - loss: 2.1968 - acc: 0.2500
Epoch 8/500
 - 0s - loss: 2.1941 - acc: 0.2500
Epoch 9/500
 - 0s - loss: 2.1914 - acc: 0.2500
Epoch 10/500
 - 0s - loss: 2.1887 - acc: 0.2500
Epoch 11/500
 - 0s - loss: 2.1860 - acc: 0.2500
Epoch 12/500
 - 0s - loss: 2.1833 - acc: 0.2500
Epoch 13/500
 - 0s - loss: 2.1806 - acc: 0.3750
Epoch 14/500
 - 0s - loss: 2.1779 - acc: 0.3750
Epoch 15/500
 - 0s - loss: 2.1751 - acc: 0.3750
Epoch 16/500
 - 0s - loss: 2.1724 - acc: 0.3750
Epoch 17/500
 - 0s - loss: 2.1697 - acc: 0.3750
Epoch 18/500
 - 0s - loss: 2.1669 - acc: 0.3750
Epoch 19/500
 - 0s - loss: 2.1642 - acc: 0.3750
Epoch 20/500
 - 0s - loss: 2.1614 - acc: 0.3750
Epoch 21/500
 - 0s - loss: 2.1586 - acc: 

Epoch 171/500
 - 0s - loss: 1.1110 - acc: 0.8750
Epoch 172/500
 - 0s - loss: 1.1026 - acc: 0.8750
Epoch 173/500
 - 0s - loss: 1.0943 - acc: 0.8750
Epoch 174/500
 - 0s - loss: 1.0861 - acc: 0.8750
Epoch 175/500
 - 0s - loss: 1.0778 - acc: 0.8750
Epoch 176/500
 - 0s - loss: 1.0697 - acc: 0.8750
Epoch 177/500
 - 0s - loss: 1.0616 - acc: 0.8750
Epoch 178/500
 - 0s - loss: 1.0535 - acc: 0.8750
Epoch 179/500
 - 0s - loss: 1.0455 - acc: 0.8750
Epoch 180/500
 - 0s - loss: 1.0376 - acc: 0.8750
Epoch 181/500
 - 0s - loss: 1.0297 - acc: 0.8750
Epoch 182/500
 - 0s - loss: 1.0219 - acc: 0.8750
Epoch 183/500
 - 0s - loss: 1.0141 - acc: 0.8750
Epoch 184/500
 - 0s - loss: 1.0064 - acc: 0.8750
Epoch 185/500
 - 0s - loss: 0.9988 - acc: 0.8750
Epoch 186/500
 - 0s - loss: 0.9912 - acc: 0.8750
Epoch 187/500
 - 0s - loss: 0.9837 - acc: 0.8750
Epoch 188/500
 - 0s - loss: 0.9763 - acc: 0.8750
Epoch 189/500
 - 0s - loss: 0.9689 - acc: 0.8750
Epoch 190/500
 - 0s - loss: 0.9615 - acc: 0.8750
Epoch 191/500
 - 0s 

Epoch 339/500
 - 0s - loss: 0.3965 - acc: 0.8750
Epoch 340/500
 - 0s - loss: 0.3948 - acc: 0.8750
Epoch 341/500
 - 0s - loss: 0.3932 - acc: 0.8750
Epoch 342/500
 - 0s - loss: 0.3916 - acc: 0.8750
Epoch 343/500
 - 0s - loss: 0.3900 - acc: 0.8750
Epoch 344/500
 - 0s - loss: 0.3885 - acc: 0.8750
Epoch 345/500
 - 0s - loss: 0.3869 - acc: 0.8750
Epoch 346/500
 - 0s - loss: 0.3854 - acc: 0.8750
Epoch 347/500
 - 0s - loss: 0.3839 - acc: 0.8750
Epoch 348/500
 - 0s - loss: 0.3823 - acc: 0.8750
Epoch 349/500
 - 0s - loss: 0.3808 - acc: 0.8750
Epoch 350/500
 - 0s - loss: 0.3794 - acc: 0.8750
Epoch 351/500
 - 0s - loss: 0.3779 - acc: 0.8750
Epoch 352/500
 - 0s - loss: 0.3764 - acc: 0.8750
Epoch 353/500
 - 0s - loss: 0.3750 - acc: 0.8750
Epoch 354/500
 - 0s - loss: 0.3736 - acc: 0.8750
Epoch 355/500
 - 0s - loss: 0.3721 - acc: 0.8750
Epoch 356/500
 - 0s - loss: 0.3707 - acc: 0.8750
Epoch 357/500
 - 0s - loss: 0.3693 - acc: 0.8750
Epoch 358/500
 - 0s - loss: 0.3680 - acc: 0.8750
Epoch 359/500
 - 0s 

In [34]:
def predict_next_word(model,t,current_word):
    encoded=t.texts_to_sequences([current_word])[0]
    encoded=np.array(encoded)
    result=model.predict_classes(encoded,verbose=0)
    for word,index in t.word_index.items():
        if index==result:
            return word

In [35]:
predict_next_word(model,t,'먹으러')

'갈래'

In [36]:
def sentencec_generation(model,t,current_word,n):
    init_word=current_word
    sentence=''
    for _ in range(n):
        encoded=t.texts_to_se

In [45]:
def sentence_generatoin(model,t,current_word,n):
    init_word=current_word
    sentence=''
    for _ in range(n):
        encoded=t.texts_to_sequences([current_word])[0]
        encoded=np.array(encoded)
        result=model.predict_classes(encoded,verbose=0)
        
        for word, index in t.word_index.items():
            if index==result:
                break
        current_word=word
        sentence=sentence+' ' +word
    sentence=init_word+sentence
    return sentence

In [46]:
sentence_generatoin(model,t,'먹으러',6)

'먹으러 갈래 메뉴는 햄버거 점심 먹으러 갈래'

* 문맥 학습


In [63]:

text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""
from keras_preprocessing.text import Tokenizer
t=Tokenizer()
t.fit_on_texts([text])
encoded=t.texts_to_sequences([text])[0]



In [64]:
vocab_size=len(t.word_index)+1


In [65]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [66]:
sequences=list()
for line in text.split('\n'):
    encoded=t.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence=encoded[:i+1]
        sequences.append(sequence)
        
        
        

In [69]:
print(len(sequences))

11


In [70]:
print(max(len(i) for i in sequences))

6


padding으로 input 길이 맞춰줌

In [76]:
from keras.preprocessing.sequence import pad_sequences
sequences=pad_sequences(sequences,maxlen=6,padding='pre')

In [77]:

print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [78]:
import numpy as np
sequenes=np.array(sequences)
X=sequences[:,:-1]
y=sequences[:,-1]

In [79]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [80]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [81]:
from keras.utils import to_categorical
y=to_categorical(y,num_classes=vocab_size)

In [83]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [90]:
from keras.layers import Embedding, Dense, SimpleRNN
from keras.models import Sequential

model=Sequential()
model.add(Embedding(vocab_size,10,input_length=5))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=2)

Epoch 1/200
 - 1s - loss: 2.4871 - acc: 0.0909
Epoch 2/200
 - 0s - loss: 2.4715 - acc: 0.1818
Epoch 3/200
 - 0s - loss: 2.4562 - acc: 0.2727
Epoch 4/200
 - 0s - loss: 2.4409 - acc: 0.2727
Epoch 5/200
 - 0s - loss: 2.4256 - acc: 0.2727
Epoch 6/200
 - 0s - loss: 2.4102 - acc: 0.3636
Epoch 7/200
 - 0s - loss: 2.3946 - acc: 0.4545
Epoch 8/200
 - 0s - loss: 2.3787 - acc: 0.3636
Epoch 9/200
 - 0s - loss: 2.3625 - acc: 0.4545
Epoch 10/200
 - 0s - loss: 2.3457 - acc: 0.4545
Epoch 11/200
 - 0s - loss: 2.3284 - acc: 0.4545
Epoch 12/200
 - 0s - loss: 2.3104 - acc: 0.4545
Epoch 13/200
 - 0s - loss: 2.2917 - acc: 0.4545
Epoch 14/200
 - 0s - loss: 2.2722 - acc: 0.4545
Epoch 15/200
 - 0s - loss: 2.2519 - acc: 0.4545
Epoch 16/200
 - 0s - loss: 2.2306 - acc: 0.4545
Epoch 17/200
 - 0s - loss: 2.2084 - acc: 0.4545
Epoch 18/200
 - 0s - loss: 2.1853 - acc: 0.4545
Epoch 19/200
 - 0s - loss: 2.1612 - acc: 0.4545
Epoch 20/200
 - 0s - loss: 2.1363 - acc: 0.4545
Epoch 21/200
 - 0s - loss: 2.1105 - acc: 0.4545
E

Epoch 171/200
 - 0s - loss: 0.1808 - acc: 1.0000
Epoch 172/200
 - 0s - loss: 0.1779 - acc: 1.0000
Epoch 173/200
 - 0s - loss: 0.1751 - acc: 1.0000
Epoch 174/200
 - 0s - loss: 0.1723 - acc: 1.0000
Epoch 175/200
 - 0s - loss: 0.1696 - acc: 1.0000
Epoch 176/200
 - 0s - loss: 0.1669 - acc: 1.0000
Epoch 177/200
 - 0s - loss: 0.1642 - acc: 1.0000
Epoch 178/200
 - 0s - loss: 0.1616 - acc: 1.0000
Epoch 179/200
 - 0s - loss: 0.1590 - acc: 1.0000
Epoch 180/200
 - 0s - loss: 0.1565 - acc: 1.0000
Epoch 181/200
 - 0s - loss: 0.1540 - acc: 1.0000
Epoch 182/200
 - 0s - loss: 0.1515 - acc: 1.0000
Epoch 183/200
 - 0s - loss: 0.1491 - acc: 1.0000
Epoch 184/200
 - 0s - loss: 0.1467 - acc: 1.0000
Epoch 185/200
 - 0s - loss: 0.1444 - acc: 1.0000
Epoch 186/200
 - 0s - loss: 0.1421 - acc: 1.0000
Epoch 187/200
 - 0s - loss: 0.1398 - acc: 1.0000
Epoch 188/200
 - 0s - loss: 0.1376 - acc: 1.0000
Epoch 189/200
 - 0s - loss: 0.1354 - acc: 1.0000
Epoch 190/200
 - 0s - loss: 0.1333 - acc: 1.0000
Epoch 191/200
 - 0s 

In [93]:
def sentence_generation(model,t,current_word,n):
    init_word=current_word
    sentence=''
    for _ in range(n):
        encoded=t.texts_to_sequences([current_word])[0]
        encoded=pad_sequences([encoded],maxlen=5,padding='pre')
        result=model.predict_classes(encoded,verbose=0)
        for word, index in t.word_index.items():
            if index==result:
                break
                
        current_word=current_word+' '+word
        sentence=sentence+' '+word
    sentence=init_word+sentence
    return sentence

In [94]:
print(sentence_generation(model,t,'경마장에',4))

경마장에 있는 말이 뛰고 있다


In [95]:
print(sentence_generation(model,t,'그의',2))

그의 말이 법이다


In [96]:
sentence_generation(model,t,'가는',5)

'가는 말이 고와야 오는 말이 곱다'

# lstm-바닐라 rnn, simple rnn 단점보완



In [98]:
import pandas as pd
df=pd.read_csv(r'C:\Users\Affinity\Downloads\nyt-comments\ArticlesMarch2018.csv')

In [102]:
df['headline'].isnull().values.any()

False

In [103]:
headline=[]
headline.extend(list(df.headline.values))
headline[:5]

['Virtual Coins, Real Resources',
 'U.S. Advances Military Plans for North Korea',
 'Mr. Trump and the ‘Very Bad Judge’',
 'To Erase Dissent, China Bans Pooh Bear and ‘N’',
 'Loans Flowed to Kushner Cos. After Visits to the White House']

In [107]:
from string import punctuation
def repreprocessing(s):
    s=s.encode('utf8').decode('ascii','ignore')
    return ''.join(c for c in s if c not in punctuation)

text=[repreprocessing(x) for x in headline]
text[:5]

['Virtual Coins Real Resources',
 'US Advances Military Plans for North Korea',
 'Mr Trump and the Very Bad Judge',
 'To Erase Dissent China Bans Pooh Bear and N',
 'Loans Flowed to Kushner Cos After Visits to the White House']

In [108]:
from keras_preprocessing.text import Tokenizer
t=Tokenizer()
t.fit_on_texts(text)
vocab_size=len(t.word_index)+1
print(vocab_size)

3583


In [110]:
sequences=[]

for line in text:
    encoded=t.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence=encoded[:i+1]
        sequences.append(sequence)
sequences[:11]

[[1120, 1121],
 [1120, 1121, 117],
 [1120, 1121, 117, 1122],
 [32, 1123],
 [32, 1123, 590],
 [32, 1123, 590, 393],
 [32, 1123, 590, 393, 7],
 [32, 1123, 590, 393, 7, 62],
 [32, 1123, 590, 393, 7, 62, 71],
 [118, 11],
 [118, 11, 6]]

인덱스에 해당하는 단어

In [111]:
index_to_word={}
for key,value in t.word_index.items():
    
    index_to_word[value]=key
    
index_to_word[582]

'journalism'

In [112]:
max_len=max(len(l) for l in sequences)
print(max_len)

18


In [113]:
from keras.preprocessing.sequence import pad_sequences
sequences=pad_sequences(sequences,maxlen=max_len, padding='pre')
print(sequences[:3])


[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0 1120 1121]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0 1120 1121  117]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
  1120 1121  117 1122]]


In [115]:
import numpy as np
sequences=np.array(sequences)
X=sequences[:,:-1]
y=sequences[:,-1]

In [117]:
print(X[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0 1120]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0 1120 1121]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
  1120 1121  117]]


In [121]:
print(y[:3])

[1121  117 1122]


In [122]:
from keras.utils import to_categorical
y=to_categorical(y,num_classes=vocab_size)

In [123]:
from keras.layers import Embedding, Dense, LSTM
from keras.models import Sequential

model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X,y,epochs=200,verbose=2)

Epoch 1/200
 - 8s - loss: 7.6492 - acc: 0.0315
Epoch 2/200
 - 7s - loss: 7.1084 - acc: 0.0346
Epoch 3/200
 - 7s - loss: 6.9692 - acc: 0.0417
Epoch 4/200
 - 7s - loss: 6.8440 - acc: 0.0449
Epoch 5/200
 - 7s - loss: 6.6960 - acc: 0.0473
Epoch 6/200
 - 7s - loss: 6.5422 - acc: 0.0495
Epoch 7/200
 - 7s - loss: 6.3885 - acc: 0.0547
Epoch 8/200
 - 7s - loss: 6.2251 - acc: 0.0570
Epoch 9/200
 - 8s - loss: 6.0692 - acc: 0.0593
Epoch 10/200
 - 7s - loss: 5.9127 - acc: 0.0616
Epoch 11/200
 - 7s - loss: 5.7601 - acc: 0.0632
Epoch 12/200
 - 7s - loss: 5.6057 - acc: 0.0681
Epoch 13/200
 - 7s - loss: 5.4523 - acc: 0.0746
Epoch 14/200
 - 7s - loss: 5.3004 - acc: 0.0782
Epoch 15/200
 - 8s - loss: 5.1511 - acc: 0.0859
Epoch 16/200
 - 7s - loss: 5.0069 - acc: 0.0927
Epoch 17/200
 - 7s - loss: 4.8631 - acc: 0.1014
Epoch 18/200
 - 8s - loss: 4.7237 - acc: 0.1118
Epoch 19/200
 - 8s - loss: 4.5882 - acc: 0.1263
Epoch 20/200
 - 8s - loss: 4.4575 - acc: 0.1465
Epoch 21/200
 - 8s - loss: 4.3281 - acc: 0.1626
E

Epoch 171/200
 - 8s - loss: 0.2968 - acc: 0.9110
Epoch 172/200
 - 8s - loss: 0.2972 - acc: 0.9082
Epoch 173/200
 - 8s - loss: 0.2949 - acc: 0.9080
Epoch 174/200
 - 8s - loss: 0.2913 - acc: 0.9085
Epoch 175/200
 - 8s - loss: 0.2909 - acc: 0.9077
Epoch 176/200
 - 8s - loss: 0.2908 - acc: 0.9087
Epoch 177/200
 - 8s - loss: 0.2920 - acc: 0.9093
Epoch 178/200
 - 8s - loss: 0.2892 - acc: 0.9098
Epoch 179/200
 - 8s - loss: 0.2926 - acc: 0.9089
Epoch 180/200
 - 8s - loss: 0.3222 - acc: 0.9027
Epoch 181/200
 - 8s - loss: 0.3112 - acc: 0.9058
Epoch 182/200
 - 8s - loss: 0.3295 - acc: 0.9016
Epoch 183/200
 - 8s - loss: 0.3055 - acc: 0.9059
Epoch 184/200
 - 8s - loss: 0.2856 - acc: 0.9079
Epoch 185/200
 - 8s - loss: 0.2834 - acc: 0.9098
Epoch 186/200
 - 9s - loss: 0.2810 - acc: 0.9101
Epoch 187/200
 - 8s - loss: 0.2797 - acc: 0.9100
Epoch 188/200
 - 8s - loss: 0.2789 - acc: 0.9085
Epoch 189/200
 - 8s - loss: 0.2797 - acc: 0.9093
Epoch 190/200
 - 8s - loss: 0.2797 - acc: 0.9091
Epoch 191/200
 - 8s 

In [134]:
def sentence_generation(model, t, current_word,n):
    init_word=current_word
    sentence=''
    for _ in range(n):
        encoded=t.texts_to_sequences([current_word])[0]
        
        encoded=pad_sequences([encoded],maxlen=17,padding='pre')
        
        result=model.predict_classes(encoded,verbose=0)
        for word,index in t.word_index.items():
            if index==result:
                break
                
        current_word=current_word+' '+word
        sentence=sentence+' ' +word
        
    sentence=init_word+sentence
    
    
    return sentence

In [135]:
print(sentence_generation(model,t,'you',10))



you will not destroy america trumps targets fire back for trumps


In [136]:
print(sentence_generation(model,t,'how',10))

how to turn your renovation into a vacation short on the


In [1]:
def sentence_generator(model,t,current_word,n):
    init_word=current_word
    sentense=''
    for _ in range(n):
        encoded=t.texts_to_sequences([current_word])[0]
        encoded=np.array(encoded)
        result=model.predict_classes(encoded,verbose=0)
        
        for word, index in t.word_index.items():
            if index==result:
                break
                
        current_word=word
        sentence=sentence+' '+word
        
    sentence=init_word+sentence
    return sentence

In [2]:
sentence_generator(mode,t,'First',5)

NameError: name 'model' is not defined