In [32]:
import os
import numpy as np
import pandas as pd

In [146]:
path_test='C:/Users\Affinity/수행평가1/digits/testDigits/'
path_train='C:/Users\Affinity/수행평가1/digits/trainingDigits/'

test_file_list=os.listdir(path_test)
train_file_list=os.listdir(path_train)


test_data=np.array(np.array(pd.read_csv(path_test+test_file_list[0])).T)  #초기데이터를 첫번째데이터로 설정



In [147]:
#테스트 데이터 생성

for i in range(1,len(test_file_list)):
    test_data=np.vstack([test_data,np.array(pd.read_csv(path_test+test_file_list[i])).T])

In [142]:
#테스트 라벨 생성

test_label=np.array(test_file_list[0][0])

for i in range(1,len(test_file_list)):
    test_label=np.vstack([test_label,test_file_list[i][0]])

In [144]:
test_label.shape

(946, 1)

In [57]:
#학습 데이터 생성
train_data=np.array(np.array(pd.read_csv(path_train+train_file_list[0])).T)
for i in range(1,len(train_file_list)):
    train_data=np.vstack([train_data,np.array(pd.read_csv(path_train+train_file_list[i])).T])

# 학습라벨 생성

train_label=np.array((train_file_list[0][0]))

for i in range(1,len(train_file_list)):
    train_label=np.vstack([train_label,train_file_list[i][0]])

In [75]:
len(train_data[0][0])

32

In [71]:
train_data[0][0]

'00000000000011111110000000000000'

In [64]:
train_label.shape

(1934, 1)

In [148]:
test_data.shape

(946, 31)

In [149]:
td=np.array([])
sep_test_data=np.array([])
for j in range(len(test_data)):
    for i in range(len(test_data[0])):
        for k in range(len(test_data[0][0])):
            td=np.append(td,int(test_data[j][i][k]))
    if j==0:
        sep_test_data=np.append(sep_test_data,td)
        td=np.array([])
    else:
        sep_test_data=np.vstack([sep_test_data,td])
        td=np.array([])

In [88]:
test_data

array([['00000000000011111100000000000000',
        '00000000000111111111000000000000',
        '00000000011111111111000000000000', ...,
        '00000000000111111111111100000000',
        '00000000000011111111110000000000',
        '00000000000000111110000000000000'],
       ['00000000000111111110000000000000',
        '00000000001111111111100000000000',
        '00000000001111111111110000000000', ...,
        '00000000001111111000000000000000',
        '00000000001111100000000000000000',
        '00000000000100000000000000000000'],
       ['00000000001111000000000000000000',
        '00000000001111000000000000000000',
        '00000000011111100000000000000000', ...,
        '00000000001111111111110000000000',
        '00000000000111111111100000000000',
        '00000000000011111100000000000000'],
       ...,
       ['00000000111111111000000000000000',
        '00000001111111111100000000000000',
        '00000011111111111111100000000000', ...,
        '00000001111111111111111100000000

In [89]:
np.tile([1,1],(2,1))

array([[1, 1],
       [1, 1]])

In [119]:
int(train_data[0][0][0])

0

In [121]:
td=np.array([])
sep_train_data=np.array([])
for j in range(len(train_data)):
    for i in range(len(train_data[0])):
        for k in range(len(train_data[0][0])):
            td=np.append(td,int(train_data[j][i][k]))
    if j==0:
        sep_train_data=np.append(sep_train_data,td)
        td=np.array([])
    else:
        sep_train_data=np.vstack([sep_train_data,td])
        td=np.array([])

In [133]:
len(train_data)

1934

In [152]:
sep_test_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [135]:
train_label.shape


(1934, 1)

In [150]:
sep_train_data.shape

(1934, 992)

In [137]:
test_label.shape

(946, 1)

NameError: name 'iteritems' is not defined

In [286]:
def clsfy(inx,dataset,label,k):
    m=len(dataset)   #데이티셋의 행크기 추출
    print(m)
    dffMat=np.tile(inx,(m,1))-dataset   #인풋데이터를  m행으로 만들어주고 dataset을빼준다.
    print('dffMat=',dffMat)
    sqDiffMat=dffMat**2  #거리를 구하기위해 제곱
    print('sqDiffMat=',sqDiffMat)
    sqDistance=sqDiffMat.sum(axis=1)  # (x1-x1')^2 + (x2-x2')^2 ......
    print('sqDistance=',sqDistance)
    Distance=np.array(sqDistance**0.5) #루트해준다
    print('Distance=',Distance)
    sortedDistance=Distance.argsort()  #몇번째로 가까운지 알려준다
    print(sortedDistance)               
    classCount={}
    
    for i in range(k):
        for j in sortedDistance:
                   if sortedDistance==i:    #  0번째,1번쨰,...k번쨰 인 인덱스알려준다.
                        votelabel=label[j]
                        classCount[votelabel]=classCount.get(votelabel,0)+1 #라벨 나올때마다 +1씩 (투표)
    print(classCount)
    sortedClasscount=sorted(classCount.items(),key=classCount.values(),reverse=True) #가장높은득표받은놈 위로
                        
                       
    return sortedClasscount[0][0]                    
    
        
    
                   
    
    

In [287]:
a=np.array([1,2])
b=np.array([[2,3],[4,5],[6,7],[3,2]])
c=np.array(['a','a','b','b'])

In [283]:
q=np.array([1,2,11,3])

In [293]:
def clsfy2(inx,dataset,label,k):
    m=len(dataset)   #데이티셋의 행크기 추출
    print(m)
    dffMat=np.tile(inx,(m,1))-dataset

In [290]:
clsfy(a,b,c,3)

4
dffMat= [[-1 -1]
 [-3 -3]
 [-5 -5]
 [-2  0]]
sqDiffMat= [[ 1  1]
 [ 9  9]
 [25 25]
 [ 4  0]]
sqDistance= [ 2 18 50  4]
Distance= [1.41421356 4.24264069 7.07106781 2.        ]
[0 3 1 2]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [291]:
sep_test_data[0].shape

(992,)

In [292]:
test_label.shape

(946, 1)

In [249]:
def handwritingtest(k):
    errorcount=0
    for i in range(0,946,30):  #30씩 시험
        classfierresult=clsfy(sep_test_data[i].T,sep_train_data,train_label,k)
        print('the predict is {}, the real answer is {}'.format(classfierresult,test_label))
        if classfierresult!=test_label: errorcount+=1
    print('total error is {}'.format(errorcount))
    print('the error rate is{}'.format(errorcount/31))   #946/30 =31.53333...

In [237]:
handwritingtest(3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()