In [1]:
import numpy as np


In [7]:
import pandas as pd

In [11]:
a=np.random.randn(3,2)

In [12]:
a.shape, a.dtype

((3, 2), dtype('float64'))

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [17]:
s1=[1,2,3,4]
s2=[33,25,74,78]
np.array(s1)

array([1, 2, 3, 4])

In [18]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [37]:
vec_x=np.array(s1) #벡터
mat_A=np.array([s1,s2]) #행렬

mat_c=np.asarray(mat_A)

In [26]:
vec_x.shape , vec_x.dtype

((4,), dtype('int32'))

In [28]:
np.asarray(s1)   #s1을 어레이로 바꿈

array([1, 2, 3, 4])

In [34]:
vec_y=np.asarray(s2)    #s1, s2를 그대로 어레이로 바꿈
mat_b=np.asarray(s1)

In [39]:
print(id(mat_A),id(mat_b),id(mat_c))   #a,b 아이디값이 다르다, 이미 어레이인걸 에스어레이하면 같은객체로취급(id(mat_A)=id(mat_c))

2498163608672 2498161094944 2498163608672


In [42]:
vx=np.arange(1,10,2)

In [43]:
vx

array([1, 3, 5, 7, 9])

In [48]:
np.zeros(4)   #원소들이 0이고 크기가4인 벡터

array([0., 0., 0., 0.])

In [49]:
np.zeros((4,5))  #원소가0이고 4x5인 행렬

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.zeros_like(mat_A)   #mat_A랑 크기가같은 0로 행렬 생성

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
np.eye(5)   #5x5 항등행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
s1=[1,2,3,4]
s2=[33.4,25.2,74.1,78.4]
np.array(s1)
vecx=np.array(s1,dtype=np.string_)  #강제로 문자열로 바꿈, 디폴트는 정수형
print(vecx,vecx.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [57]:
vecx=np.array(s1)  #강제로 문자열로 바꿈, 디폴트는 정수형
print(vecx,vecx.dtype)

[1 2 3 4] int32


In [59]:
vecx.astype(np.float64)

array([1., 2., 3., 4.])

In [64]:
mat=np.array([s1,s2])
print(mat,mat.dtype)
mat=mat.astype(np.int16)
print(mat,mat.dtype)

[[ 1.   2.   3.   4. ]
 [33.4 25.2 74.1 78.4]] float64
[[ 1  2  3  4]
 [33 25 74 78]] int16


* 배열과 스칼라 연산

In [70]:
vec=np.array(s1)
print(vec,2*vec,vec/4)    #각각 원소에 동일한 연산을해줌
mat=np.array([s1,s2])


print(mat)
print(2*mat,mat+10)

[1 2 3 4] [2 4 6 8] [0.25 0.5  0.75 1.  ]
[[ 1.   2.   3.   4. ]
 [33.4 25.2 74.1 78.4]]
[[  2.    4.    6.    8. ]
 [ 66.8  50.4 148.2 156.8]] [[11.  12.  13.  14. ]
 [43.4 35.2 84.1 88.4]]


In [73]:
s1=[1,2,3,4]
s2=[33,25,74,78]

vec1=np.array(s1)
vec2=np.array(s2)
print(vec1*vec2)  #벡터곱이 아니라 같은위치원소끼리 곱해버림


[ 33  50 222 312]


In [77]:
mat1=np.array([s1,s2])
mat2=np.array([[2,5,1,2],[4,2,3,1]])    
mat1*mat2    #우리가 아는 행렬곱이 아니라 같은위치 원ㅅ끼리 곱

array([[  2,  10,   3,   8],
       [132,  50, 222,  78]])

In [78]:
mat1[2:4]

array([], shape=(0, 4), dtype=int32)

In [107]:
s1=[1,2,3,4,2,44,12,43]
s2=[33,25,74,78,1,3,4,5]

vec=np.array(s1)

sub_vec1=vec[1:5]   #서브벡터(벡터일부만 가져온거) 원소를바꾸면 원래벡터도 수정됌
sub_vec2=vec[1:5].copy
print(s1[4],vec[4])   #인덱싱
s1[1:3], vec[1:3]    #슬라이싱

#s1[4]=999 ; vec[4]=999

s1,vec

s1[1:3]=[100] 
vec[1:3]=100

print(s1,vec)   #차이확인

2 2
[1, 100, 4, 2, 44, 12, 43] [  1 100 100   4   2  44  12  43]


In [100]:
s1[1:10]=1

TypeError: can only assign an iterable

In [109]:
s1=[1,2,3,4,2,44,12,43,1]
s2=[78,1,3,4,5,2,121,32,45]
s3=[10,20,30,40,50,60,70,80,90]
vec=np.array(s1)

sub_vec1=vec[1:5]   #서브벡터(벡터일부만 가져온거) 원소를바꾸면 원래벡터도 수정됌
sub_vec2=vec[1:5].copy()   # 얘는원본에 영향안미침

In [110]:
sub_vec1[0]=928

In [112]:
vec   #원본도 바뀜

array([  1, 928,   3,   4,   2,  44,  12,  43])

In [114]:
#3차원행렬

s1=[1,2,3,4,2,44,12,43,1]
s2=[78,1,3,4,5,2,121,32,45]
s3=[10,20,30,40,50,60,70,80,90]

A=np.array([s1,s2,s3])

In [124]:
print(A[1])   #1행추출
print(A[1,5]) #1행 5열 추출
print(A[1][5]) #1행 5열 추출
print(A[:2,2:5])  # (0~1행),(2~4열)  추출
print(A[:2][2:5]) #슬라이싱할때는 이게안됌
print(A[:2][:,2:5])  #이런식으로 해줘야됌(앞에서뽑힌 모든행을 선언해줘야됌)

[ 78   1   3   4   5   2 121  32  45]
2
2
[[3 4 2]
 [3 4 5]]
[]
[[3 4 2]
 [3 4 5]]


In [130]:
s11=[1,2,3,4] ; s12=[10,20,30,40]; s13=[100,200,300,400]
s21=[11,22,33,44]; s22=[12,22,32,42]; s23=[31,32,33,34]

In [139]:
L=np.array([[s11,s12,s13],[s21,s22,s23]])

In [141]:
L

array([[[  1,   2,   3,   4],
        [ 10,  20,  30,  40],
        [100, 200, 300, 400]],

       [[ 11,  22,  33,  44],
        [ 12,  22,  32,  42],
        [ 31,  32,  33,  34]]])

In [142]:
L.shape

(2, 3, 4)

In [145]:
print(L[0,1,2])
print(L[0][1,2])


30
30


In [147]:
print(L[:,:2,:2])
print(L[:2,1])

[[[ 1  2]
  [10 20]]

 [[11 22]
  [12 22]]]
[[10 20 30 40]
 [12 22 32 42]]


In [148]:
sub_L1=L[:2,1]     #뷰 
sub_L2=L[:2,1].copy()   #카피

In [150]:
print(sub_L1, sub_L2)

[[10 20 30 40]
 [12 22 32 42]] [[10 20 30 40]
 [12 22 32 42]]


In [151]:
L.shape

(2, 3, 4)

In [156]:
mat1=np.array([s11,s12,s13])
mat1

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [160]:
print(mat1[1],'\n',mat1[[False,True,False]])   #논리값으로 인덱싱하기
print(mat1[mat1>10])   # 10넘는값만 추출

[10 20 30 40] 
 [[10 20 30 40]]
[ 20  30  40 100 200 300 400]


In [171]:
gender=np.array(['남','남','여','여','남','여'])
s11=[1,2,3,4];s12=[10,40,20,60];s13=[4,2,5,4]
s21=[1,2,3,4];s22=[110,140,120,160];s23=[224,322,125,34]


mat=np.array([s11,s12,s13,s21,s22,s23])
print(gender,'mat:',mat)
result=gender=='남'
print('result:',result)
male=mat[result]

female=mat[~result]
print('male:',male)

['남' '남' '여' '여' '남' '여'] mat: [[  1   2   3   4]
 [ 10  40  20  60]
 [  4   2   5   4]
 [  1   2   3   4]
 [110 140 120 160]
 [224 322 125  34]]
result: [ True  True False False  True False]
male: [[  1   2   3   4]
 [ 10  40  20  60]
 [110 140 120 160]]


In [166]:
mat[mat<10]*10

array([10, 20, 30, 40, 40, 20, 50, 40, 10, 20, 30, 40])

* 펜시 인덱싱

In [200]:
ex=np.random.randn(6,7)

print('ex:',ex)

print('fency',ex[[5,0,2],[3,1,4]])  # 5행 3열, 0행1열, 2행 4열  추출
print('fency2',ex[[5,0,2]][:,[3,1,4]])  #앞에뽑힌전체 라는걸 선언해줘야함 (5,0,2열 전체중에 3열,1열, 4열)


ex: [[ 0.66533532 -1.6451255   0.37073953 -0.67334694  0.46945794 -2.88112451
  -0.51205161]
 [-1.31187668  0.65118594 -0.87425186 -2.15543204  1.77050233  1.26316461
   0.01741022]
 [ 1.09750137 -0.97796097  0.50654288 -0.8861273  -1.06199846  0.25365003
   1.39377241]
 [ 1.80450761  0.83500925 -0.18447119  1.15054775  1.33147526 -0.50039992
   0.71685746]
 [ 0.9197221  -0.75026886 -0.62315306 -0.78326145 -0.42824067  0.71592013
   0.72927134]
 [ 0.54787469 -0.85025229  1.22511636 -0.56988924  0.09936441  1.08816098
   1.16072242]]
fency [-0.56988924 -1.6451255  -1.06199846]
fency2 [[-0.56988924 -0.85025229  0.09936441]
 [-0.67334694 -1.6451255   0.46945794]
 [-0.8861273  -0.97796097 -1.06199846]]


* 전치/축바꾸기

In [205]:
ex=np.arange(24).reshape(2,4,3)

In [209]:
print(ex) #(2,4,3) =전치=>  (3,4,2)
ex.T

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [213]:
print(ex,'\n\n\n\n\n',ex.transpose(2,0,1))  #열을층 층을행 행을열로 변경 2,4,3 -> 3,2,4

#층헹열

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 




 [[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


In [215]:
arr2=arr.T


In [217]:
arr4=arr.swapaxes(2,0)  #2(열)과 0(층)을 바꾼다

arr4


array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

* 범용 함수: 데이터 원소별로 연산수행

NAN: 누락데이터,결측안된데이터

In [218]:
np.array([1,2,3,np.inf,np.nan])

array([ 1.,  2.,  3., inf, nan])

In [229]:
A=np.arange(18).reshape(3,6)
B=np.random.randn(3,6)
print(A,'\n',B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 
 [[ 0.51255324  0.24637472 -0.59074617  1.40264838 -1.02438185 -0.36826071]
 [ 1.78068282 -0.46254835 -0.14420814 -0.33269734  1.47994367 -0.14355034]
 [ 0.51934966 -0.69067522  2.13457244 -1.65582886 -1.07465757 -0.7857012 ]]


In [225]:
print(np.abs(B))  #각원소를 절대값으로 돌려줌

[[0.44501549 0.26324325 0.13639905 0.98214911 0.9503875  1.58463866
  0.00278118]
 [0.11798275 1.30134617 0.34808006 0.01556604 1.44120764 0.15791479
  2.08687425]
 [1.33928248 1.71725014 1.65154642 0.11493376 0.81198077 0.7701558
  0.63340294]]


In [227]:
print(np.isfinite(B))   #요소가 유한하냐


[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [231]:
print(np.multiply(A,B))
print(np.power(A,B))

[[  0.           0.24637472  -1.18149233   4.20794514  -4.09752739
   -1.84130356]
 [ 10.6840969   -3.23783842  -1.15366513  -2.99427606  14.79943668
   -1.57905379]
 [  6.23219594  -8.97877792  29.88401409 -24.83743297 -17.1945212
  -13.35692033]]
[[0.00000000e+00 1.00000000e+00 6.63999396e-01 4.66910194e+00
  2.41691108e-01 5.52836627e-01]
 [2.43019185e+01 4.06538143e-01 7.40912756e-01 4.81422136e-01
  3.01956003e+01 7.08773907e-01]
 [3.63473217e+00 1.70069692e-01 2.79571768e+02 1.12874060e-02
  5.08139949e-02 1.07953024e-01]]


In [237]:
print(np.greater(A,B)
      
      

SyntaxError: unexpected EOF while parsing (<ipython-input-237-70d12ce1ae17>, line 3)

In [238]:
B[B>=0] & B[b<10]}
np.logical_and((B>=0))

SyntaxError: invalid syntax (<ipython-input-238-c6e18e29f378>, line 1)

In [245]:
xarr=np.array([1,2,3,4,5,7])
yarr=np.array([1,2,3,4,5,6])
zarr=np.array(['서울','경기','서울','인천','경기','울산'])
result=[(x if z=='서울' else y) for x,y,z in zip(xarr,yarr,zarr)]

In [241]:
result

[2.5, 2, 8.1, 4, 5]

In [248]:
result2=np.where(zarr=='서울',xarr,yarr)   #위에거편하게하기 np.where(논리식,참일때값,거짓일때값)

In [247]:
result2

array([1, 2, 3, 4, 5, 6])

In [249]:
np.where([True,False,True],[1,2,3],[99,92,91])

array([ 1, 92,  3])

In [251]:
#2차원 배열일때

np.where([[True,False],[True,False]],[[1,2],[2,3]],[[333,322],[222,132]])

array([[  1, 322],
       [  2, 132]])

where(조건, 참 ,where(조건,참,where(조건,참,거짓))

In [254]:
arr1=(10+5*np.random.randn(12)).reshape(4,3)
arr2=(10+5*np.random.randn(12)).reshape(4,3)
result=np.where(arr1>=10,arr1,np.where(arr2>10,arr2,0))
result


array([[ 0.        ,  0.        , 19.39642653],
       [15.03225222, 11.54046946,  0.        ],
       [11.88894191,  0.        , 13.72815192],
       [13.43862236,  0.        , 13.25223707]])

In [258]:
A=np.array([2,5,3,5,3,11])
B=np.array([3,4,5,6,5])
print(A.mean(),B.mean())   #골라서쓰면됌
print(np.mean(A),np.mean(B))


4.833333333333333 4.6
4.833333333333333 4.6


In [262]:
print(a.std(ddof=0),np.std(A,ddof=0))   #ddof = degree of freedom, ddof=0 이면 분산분모가 n, ddof=1이면 n-1로 나눔

0.5573399098172015 2.9674156357941426


In [264]:
A=np.array([[2,5,3],[5,3,11],[4,2,5],[3,4,2]])
B=np.array([[3,4,5],[6,5]])
print(A.mean(),B.mean())   #골라서쓰면됌
print(np.mean(A),np.mean(B))


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [285]:
A=np.array([[[2,5,3],[5,3,11]],[[4,2,5],[3,4,2]]])
A.mean(),np.mean(A)
print(A.mean(axis=0))   #(층=0, 행=1, 열=2)

[[3.  3.5 4. ]
 [4.  3.5 6.5]]


In [274]:
B=np.array([2,3,4,5,2,3,2,11,231])
print(B>10)
(B>10).sum()    #True=1, False=0

[False False False False False False False  True  True]


2

In [278]:
print((B>10).all(),(B>=10).any())

False True


In [279]:
np.sort(B)

array([  2,   2,   2,   3,   3,   4,   5,  11, 231])

In [286]:
print(A,'\n\n\n\n\n')
A.sort(axis=0)
print(A)

[[[ 2  5  3]
  [ 5  3 11]]

 [[ 4  2  5]
  [ 3  4  2]]] 





[[[ 2  2  3]
  [ 3  3  2]]

 [[ 4  5  5]
  [ 5  4 11]]]


In [289]:
np.save('qweqwe.npy',A)  #npy 파일로 저장

In [290]:
q=np.load('qweqwe.npy')  #저장한파일 불러오기

In [291]:
q

array([[[ 2,  2,  3],
        [ 3,  3,  2]],

       [[ 4,  5,  5],
        [ 5,  4, 11]]])

In [295]:
np.savez('qqqq.npz',A2d=A,B1d=B)   #압축해서 키워드로 저장

In [296]:
load_A=np.load('qqqq.npz')

In [298]:
load_A #압축해서 저장한거라 이렇게나옴=키워드 입력해줘야한다

In [300]:
load_A['A2d']

array([[[ 2,  2,  3],
        [ 3,  3,  2]],

       [[ 4,  5,  5],
        [ 5,  4, 11]]])

In [2]:
a=np.loadtxt('steel.txt',skiprows=5,delimiter='\t',usecols=(0,2))   #usecols=해당열만 가져오겠다

In [305]:
a

array([[ 81.4,  57. ],
       [122.2,  61. ],
       [101.7,  60. ],
       [175.6,  62. ],
       [150.3,  61. ],
       [ 64.8,  54. ],
       [ 92.1,  58. ],
       [113.8,  61. ]])

In [308]:
A=np.arange(8).reshape(4,2)
B=np.array([[3,5,7,2],[4,3,6,2]])
C=np.array([[2,3,4,5],[1,12,32,65],[23,4,2,1],[2,2,3,1]])

In [309]:
print(np.dot(B,A))  # 행렬곱

[[50 67]
 [42 57]]


In [312]:
np.diag(C)  #대각성분, 대각성분합=trace

array([ 2, 12,  2,  1])

In [316]:
np.rint(np.dot(C.np.lialg.inv(C)))

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [4]:
steel=np.loadtxt('steel.txt',skiprows=5,delimiter='\t')

In [5]:
steel  # 종속변수(Y) 독립변수1(X1) 독립변수2(X2)

array([[ 81.4, 195. ,  57. ],
       [122.2, 179. ,  61. ],
       [101.7, 205. ,  60. ],
       [175.6, 204. ,  62. ],
       [150.3, 201. ,  61. ],
       [ 64.8, 184. ,  54. ],
       [ 92.1, 210. ,  58. ],
       [113.8, 209. ,  61. ]])

In [12]:
Y=steel[:,0].copy()
X=steel.copy()
X[:,0]=1
b=np.linalg.lstsq(X,Y)[0]
print(steel,'\n\n\n',X,'\n\n\n\n',Y)



[[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]] 


 [[  1. 195.  57.]
 [  1. 179.  61.]
 [  1. 205.  60.]
 [  1. 204.  62.]
 [  1. 201.  61.]
 [  1. 184.  54.]
 [  1. 210.  58.]
 [  1. 209.  61.]] 



 [ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]


C:\ProgramData\Anaconda3\envs\mp\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


In [13]:
print(b*new_x)



[-554.31122321  -35.94792132  711.59956219]


In [326]:
Y

array([ 81.4, 122.2, 101.7, 175.6, 150.3,  64.8,  92.1, 113.8])

In [334]:
np.linalg.lstsq(X,Y)  #회귀변수 추정량

C:\ProgramData\Anaconda3\envs\mp\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-5.54311223e+02, -1.79739607e-01,  1.18599927e+01]),
 array([2340.88393765]),
 3,
 array([5.86352311e+02, 8.94176555e+00, 1.09839713e-01]))

In [8]:
print(np.linalg.lstsq(X,Y))   #회귀계수 , 오차제곱합, 고유값

(array([-5.54311223e+02, -1.79739607e-01,  1.18599927e+01]), array([2340.88393765]), 3, array([5.86352311e+02, 8.94176555e+00, 1.09839713e-01]))


C:\ProgramData\Anaconda3\envs\mp\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [10]:
new_x=np.array([1,200,60])  #온도가 200이고 압력이 60일때

In [11]:
print(b,new_x)

NameError: name 'b' is not defined

* 난수

In [15]:
norm_sample1=np.random.randn(20)
norm_sample2=np.random.normal(size=20)

넘파이 어레이는 같은자료만저장가능 

In [38]:
np.array([3,2,'11'])   # 다른형태로저장해도 같은형태로 바꿔서 뱉어냄  ==> 판다스로 자료다룸

array(['3', '2', '11'], dtype='<U11')